# Generated by Django 5.1.6 on 2025-03-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_rename_difficulty_interviewquestion_experience_and_more'),
        ('speech_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewquestion'),
        ),
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
    ]
