# Generated by Django 5.1.6 on 2025-03-09 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0002_alter_useranswer_question_delete_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='interview_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
