# Generated by Django 5.1.6 on 2025-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0003_useranswer_created_at_useranswer_interview_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='interview_id',
        ),
    ]
